### ISSUE TITLE
업체(Store) API 구현

### ISSUE THREAD

**Issue by hyh1016** [dnd-side-project/dnd-8th-9-backend#5]
| type | title | labels | assignees |
| :--: | :---: | :----: | :-------: |
| feature | 업체(Store) API 구현 |  feature |   hyh1016 |

## Description

주문제작 케이크 판매 업체 도메인의 API를 구현

## To Do

- [x] 업체 컨트롤러/서비스/리포지토리/엔티티 구현
- [x] 업체 생성 API 구현
- [x] 업체 조회 API 구현
- [x] 업체 수정 API 구현
- [x] 업체 삭제 API 구현

## Etc

- 업체 조회의 경우 다음을 고려하여 설계되어야 함
  - `카테고리/가격/플랫폼/수령방법` 기반 필터링
  - `추천순/인기순/리뷰많은순/당도높은순` 기반 정렬
- 업체 플랫폼의 경우 별도 테이블에서 관리됨 (StoreLink)

**Comment by minje0204** [comment]
@hyh1016 DELETE /store/{storeId} 에서 file enitity 삭제하고 있지 않는 것 같습니다. 확인 부탁드려용
